export const news = [
  { // indice = 0
    id: 1,
    autor: "Jane Doe",
    categoria: "tech",
    titulo: "Introducción a React 18",
    descripcion: "Descubre las nuevas características de React 18 y cómo pueden mejorar tu flujo de trabajo.",
    urlImagen: "https://images.unsplash.com/photo-1542831371-29b0f74f9713",
    fecha: "2023-09-24",
    textoBoton: "Leer más",
  },
  { // indice = 1
    id: 2,
    autor: "John Smith",
    categoria: "tech",
    titulo: "Mejorando el rendimiento con React",
    descripcion: "Aprende a optimizar tu aplicación React para un mejor rendimiento y experiencia de usuario.",
    urlImagen: "https://images.unsplash.com/photo-1552793494-111afe03d0ca",
    fecha: "2023-09-24",
    textoBoton: "Explorar",
  },
  {
    id: 3,
    autor: "John Doe",
    categoria: "sports",
    titulo: "Eliud Kipchoge gana el Maratón de Berlín 2023",
    descripcion: "Eliud Kipchoge, el legendario corredor keniano, ha ganado el Maratón de Berlín 2023 con un tiempo récord.",
    urlImagen: "https://static.dw.com/image/66909595_1004.webp",
    fecha: "2023-09-24",
    textoBoton: "Leer más",
  },
  {
    id: 4,
    autor: "Alice Johnson",
    categoria: "tech",
    titulo: "Hooks en React: Qué son y cómo usarlos",
    descripcion: "Una guía completa sobre Hooks en React, desde useState hasta useEffect y más.",
    urlImagen: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    fecha: "2023-09-24",
    textoBoton: "Descubrir",
  },
  {
    id: 5,
    autor: "Bob Brown",
    categoria: "tech",
    titulo: "Migrando de JavaScript a TypeScript en React",
    descripcion: "Consejos y trucos para migrar tu proyecto de React de JavaScript a TypeScript sin problemas.",
    urlImagen: "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf",
    fecha: "2023-09-24",
    textoBoton: "Leer artículo",
  },
  {
    id: 6,
    autor: "Jane Smith",
    categoria: "sports",
    titulo: "Nueva York se prepara para su maratón anual",
    descripcion: "La ciudad de Nueva York está lista para acoger a miles de corredores de todo el mundo en su maratón anual.",
    urlImagen: "https://nyc.eu/wp-content/uploads/2023/11/marathon-new-york-city.jpeg",
    fecha: "2023-11-05",
    textoBoton: "Detalles",
  },
  {
    id: 7,
    autor: "Charlie Green",
    categoria: "tech",
    titulo: "Mejores prácticas de CSS en React",
    descripcion: "Cómo organizar y escribir CSS eficiente y mantenible en tus proyectos de React.",
    urlImagen: "https://images.unsplash.com/photo-1517649763962-0c623066013b",
    fecha: "2023-11-05",
    textoBoton: "Saber más",
  },
  {
    id: 8,
    autor: "Diana White",
    categoria: "tech",
    titulo: "State Management con Redux en React",
    descripcion: "Una introducción a Redux y cómo manejar el estado de tu aplicación React de manera eficiente.",
    urlImagen: "https://images.unsplash.com/photo-1535223289827-42f1e9919769",
    fecha: "2023-11-05",
    textoBoton: "Ver detalles",
  },
  {
    id: 9,
    autor: "Carlos Pérez",
    categoria: "sports",
    titulo: "Consejos para mejorar tu tiempo en carreras de 10K",
    descripcion: "Entrenadores expertos comparten sus mejores consejos para ayudarte a mejorar tu tiempo en carreras de 10 kilómetros.",
    urlImagen: "https://station24.com.mx/img/publicaciones/publicacion-6-principal.jpg",
    fecha: "2023-07-01",
    textoBoton: "Aprende más",
  },
  {
    id: 10,
    autor: "Ethan Black",
    categoria: "tech",
    titulo: "Desarrollando componentes reutilizables en React",
    descripcion: "Guía paso a paso para crear componentes reutilizables y modulares en tus aplicaciones React.",
    urlImagen: "https://images.unsplash.com/photo-1607798748738-b15c40d33d57",
    fecha: "2023-07-01",
    textoBoton: "Aprender más",
  },
  {
    id: 11,
    autor: "Fiona Blue",
    categoria: "tech",
    titulo: "Introducción a Next.js para desarrollo de aplicaciones React",
    descripcion: "Descubre cómo Next.js puede mejorar el desarrollo de tus aplicaciones React con funcionalidades avanzadas.",
    urlImagen: "https://images.unsplash.com/photo-1593642634367-d91a135587b5",
    fecha: "2023-07-01",
    textoBoton: "Leer ahora",
  },  
  {
    id: 12,
    autor: "Laura Gómez",
    categoria: "sports",
    titulo: "La importancia de la nutrición en corredores de larga distancia",
    descripcion: "Descubre cómo una alimentación adecuada puede mejorar tu rendimiento en carreras de larga distancia.",
    urlImagen: "https://nutryt.mx/wp-content/uploads/2024/01/DALL%C2%B7E-2024-01-13-15.45.13-A-horizontal-banner-image-for-a-running-and-nutrition-article.-The-image-should-show-a-diverse-group-of-runners-of-different-ages-and-fitness-levels--1024x585.png",
    fecha: "2023-08-15",
    textoBoton: "Leer artículo",
  },
  {
    id: 13,
    autor: "George Violet",
    categoria: "tech",
    titulo: "React Native: Construyendo aplicaciones móviles con React",
    descripcion: "Aprende a utilizar React Native para crear aplicaciones móviles multiplataforma con React.",
    urlImagen: "https://images.unsplash.com/photo-1573497491208-6b1acb260507",
    fecha: "2023-08-15",
    textoBoton: "Ver más",
  },
  {
    id: 14,
    autor: "Hannah Yellow",
    categoria: "tech",
    titulo: "Testing en React: Mejores prácticas",
    descripcion: "Conoce las mejores prácticas para escribir pruebas efectivas y mantener la calidad del código en React.",
    urlImagen: "https://images.unsplash.com/photo-1593642532973-d31b6557fa68",
    fecha: "2023-08-15",
    textoBoton: "Investigar",
  },
  {
    id: 15,
    autor: "Ana Martínez",
    categoria: "sports",
    titulo: "Las mejores zapatillas para correr en 2024",
    descripcion: "Una revisión de las mejores zapatillas de running del año, basándose en comodidad, durabilidad y rendimiento.",
    urlImagen: "https://www.roadrunningreview.com/a/b/1024/1/2/100304.jpg",
    fecha: "2023-12-10",
    textoBoton: "Ver más",
  },
];